name: Testing Pipeline

on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Start Testing
        run: echo "Testing process started"

      - name: Checking Login Page
        run: echo "Login page working"

      - name: Checking Payment Module
        echo "Payment module working correctly"

      - name: Final Status
        run: echo "All checks completed successfully"
